# Generated by Django 3.2 on 2025-06-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_offer'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='wishlist',
            field=models.ManyToManyField(blank=True, related_name='wishlisted_by', to='products.Product'),
        ),
    ]
